version: "3"

services:
   db:
     image: postgres:14.5
     ports:
       - "15432:5432"
     environment:
       POSTGRES_PASSWORD: dataset
       POSTGRES_DB: dataset

   dataset:
     build:
       dockerfile: Dockerfile
       context: .
     env_file:
       - .env
     depends_on:
       - db
     ports:
       - "8080:8080"
     links:
       - db
