version: "3"

services:
   postgres:
     image: postgres:14.5
     ports:
       - "15432:5432"
     environment:
       POSTGRES_PASSWORD: dataset
       POSTGRES_DB: dataset
     networks:
       - shop

   dataset:
     build:
       dockerfile: Dockerfile
       context: .
     env_file:
       - .env
     depends_on:
       - postgres
     ports:
       - "8080:8080"
     links:
       - postgres
     networks:
       - shop

networks:
  shop:
    external:
      name: shop-net